config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

    root "home#index"  

    resources :bugs
    # resources :users 
    resources :members  



end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    # before_action :set_member, only: [:edit, :update, :show, :destroy] 
    # # before_action :authenticate_user!, except: %i[index show]

    # def index

    #     @members = User.all 
        
    # end

    # def new
    #     @member = User.new
    #     # authorize @member
    # end

    # def create
    #     # authorize @member
    #     @member = User.new(member_params)
    #     if @member.save
    #         redirect_to members_path , notice: 'member Has been created successfully'
    #     else
    #         render :new
    #     end
    # end

    # def edit 
    # end

    # def update
    #     if @member.update(member_params)
    #         redirect_to members_path , notice: 'User Has been Updated successfully'
    #     else
    #         render :edit
    #     end
    # end

    # def show 
    #     # authorize @member
    
    # end

    # def destroy
    #     if @member.destroy
    #         redirect_to members_path , notice: 'User Has been Deleted successfully'
       
    #     end 
    # end

    # private
    # def member_params
    #     params.require(:member).permit(:email, :encrypted_password,:password_confirmation, :type)
    # end

    # def set_member
    #     @member =User.find(params[:id])

    # rescue ActiveRecord::RecordNotFound => error
    #     redirect_to members_path, notice: error 
    # end


        before_action :set_user, only: [:edit, :update, :show, :destroy] 
     #   before_action :authenticate_user!, except: %i[index show]
    
        def index
    
            @members = User.all 
            
        end
    
        def new
            @member = User.new
            authorize @user
        end
    
        def create
            authorize @user
            @user = User.new(user_params)
            if @user.save
                redirect_to users_path , notice: 'User Has been created successfully'
            else
                render :new
            end
        end
    
        def edit 
        end
    
        def update
            if @user.update(user_params)
                redirect_to users_path , notice: 'User Has been Updated successfully'
            else
                render :edit
            end
        end
    
        def show 
            authorize @user
        
        end
    
        def destroy
            if @user.destroy
                redirect_to users_path , notice: 'User Has been Deleted successfully'
           
            end 
        end
    
        private
        def user_params
            params.require(:user).permit(:email, :encrypted_password,:password_confirmation, :type)
        end
    
        def set_user
            @user =User.find(params[:id])
    
        rescue ActiveRecord::RecordNotFound => error
            redirect_to users_path, notice: error 
        end
    


end

app/views/members/_form.html.erb
<%= form_with  model: user do |form| %>
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <%= form.label :email , class:"mb-2"%>
                <%= form.text_field  :email, class:"form-control form-control-lg rounded-0"%>                
                <% @user.errors.full_messages_for(:email).each do |message| %> 
                    <p class="text-danger"><%= message%> </p>
                <%end%>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <%= form.label :encrypted_password, class:"mb-2"%>
                <%= form.password_field  :encrypted_password, class:"form-control form-control-lg rounded-0"%>                
                <% @user.errors.full_messages_for(:encrypted_password).each do |message| %> 
                    <p class="text-danger"><%= message%> </p>
                <%end%>
            </div>
        </div>
    </div>

    
    <div class="row">
                    
     <div class="col-lg-6">
        <div class="form-group">
            <%= form.label :password_confirmation, class:"mb-2"%>
            <%= form.password_field  :password_confirmation, class:"form-control form-control-lg rounded-0"%>                
            <% @user.errors.full_messages_for(:password_confirmation).each do |message| %> 
                <p class="text-danger"><%= message%> </p>
            <%end%>
        </div>
    </div>
        
        <div class="col-lg-6">
            <div class="form-group">
                <%= form.label :type, class:"mb-2"%>
                <%= form.select  :type, options_for_select(User::TYPE, selected:
                user.type),{prompt: 'Select Current Role'},{ class:"form-select form-select-lg
                rounded-0" }%>
                <% @user.errors.full_messages_for(:type).each do |message| %> 
                    <p class="text-danger"><%= message%> </p>
                <%end%>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12">
            <%= form.submit class:"btn btn-primary btn-lg rounded-0 my-2" %>
            <%= link_to 'Back To User List', users_path,  class:"btn btn-outline-primary btn-lg rounded-0 my-2" %>

        </div>
        
    </div>
    
<%end%>

app/views/members/index.html.erb
<%= flash[:notice] %>
    <div class="card my-5 rounded-0">
    
        <div class="card-body">
            <h1 class="text-center"> Bug Details  </h1>
        </div>
    </div>
    <div class="col-lg-12 my-2 ">
        <%#= link_to 'Create New Bug', new_bug_path, class:"btn btn-primary btn-lg rounded-0"%>

    </div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Title </th>
            <th>Description</th>
            <th>Priority </th>
            <th>Type </th>
            <th>Actions </th>

        </tr>
    </thead>
    <tbody>
    <% @members.each do |user| %>
        <tr>
            <td><%= user.email  %></td>
            <td><%= user.encrypted_password %></td>
           
            <td><%= user.type %></td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Actions
                    </button>
                    <ul class="dropdown-menu bg-dark text-light" aria-labelledby="dropdownMenuButton1">
                            <li><%#= link_to 'edit', edit_bug_path(bug),   class:'dropdown-item bg-dark text-light rounded-0'%>
                            </li>
                            <li><%#= link_to 'View', bug_path(bug),   class:'dropdown-item bg-dark text-light rounded-0'%>
                            </li>
                            <li><%#= link_to 'delete', bug_path(bug), method: :delete, 
                            data:{confirm: "Are you sure You want to delete this bug"},
                            class:'dropdown-item bg-dark text-light rounded-0' %>
                            
                            </li>
                        </ul>
                </div>
            </td>



            
        </tr>
    <%end%>

    </tbody>

</table>

app/views/members/new.html.erb
<div class="col-lg-12">
    <div class="card my-5 rounded-0">
        <div class="card-body">
            <h1 class="text-center"> Create New User</h1>
        </div>
    </div>

   
    <%= render 'form', user: @user %>
</div>